### ISSUE TITLE
Sqitch - Add files into '/verify' folder

### ISSUE THREAD

**Issue by YingtingChen** [linz/nz-buildings#164]
### User Story

In order to use Sqitch to manage database change as a LDA I want to modify codes and add them to the `/verify` folder. 

#### Acceptance Criteria
- [ ] Follow the steps in https://github.com/linz/topo-tasks/issues/204
- [ ] Examples can be found in https://metacpan.org/pod/sqitchtutorial#Trust,-But-Verify

**Comment by dwsilk** [comment]
Merged with https://github.com/linz/nz-buildings/issues/163
