### ISSUE TITLE
Sqitch - Add files into '/revert' folder

### ISSUE THREAD

**Issue by YingtingChen** [linz/nz-buildings#165]
### User Story

In order to use Sqitch to manage database change as a LDA I want to modify codes and add them to the `/revert` folder. 

#### Acceptance Criteria
- [ ] Follow the steps in https://github.com/linz/topo-tasks/issues/204
- [ ] Revert the deployment

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by dwsilk** [comment]
Merged with https://github.com/linz/nz-buildings/issues/163
