### ISSUE TITLE
LIQA - Buildings Plugin Bug

### ISSUE THREAD

**Issue by MDavidson17** [linz/nz-buildings#181]
### Bug Description
When attempting to iterate through the qa layers in the LIQA error inspector the plugin gives an error (screenshot attached). While this appears to be a LIQA issue it is also possible something that happened with the integration of the plugin and database repositories as using the master code on the qgis-buildings-plugin repo does not give this error.

According to the api (https://qgis.org/api/2.18/classQgsCategorizedSymbolRendererV2.html) the `.symbol()` function is no longer in use after QGIS 2.18.21, This does not explain the error on our ubuntu machines as we have 2.18.16 but the QGIS version on the QA computers is 2.18.23.

#### Steps to Reproduce
1. In QGIS open buildings plugin and bulk load frame
2. run any LIQA check bulk load outlines
3. open error inspector
4. click on first building in table

#### Work Around
In order to keep QA-ing the outlines we have made a temporary fix of changing the code in LIQA in the plugins folder on our user profiles. Changing line 105 in error_inspector.py to:
`lyr_color = lyr.rendererV2().symbols()[0].color()`

#### Desktop
 - Environment: All
 - Relevant Software Versions QGIS 2.18.16, 2.18.23

#### Screenshots

![image](https://user-images.githubusercontent.com/33814653/50064035-db656400-0213-11e9-9d39-68236dc7c869.png)

**Comment by jducnuigeen** [comment]
@YingtingChen  You were right, In the function highlight_features in error_inspector.py I removed the 
`lyr_color = lyr.rendererV2().symbols()[0].color()` line 
which was previously the 
`lyr_color = lyr.rendererV2().symbol().color()` line 
and then changed
`h.setFillColor(lyr_color)`
to
`h.setFillColor(QColor(255, 255, 0, 0))`
This works on the windows QA machine running QGIS 2.18.23
Maybe @MDavidson17 can test this on hers?

**Comment by MDavidson17** [comment]
@jducnuigeen @YingtingChen  Worked on my computer too
