### ISSUE TITLE
Consistent method to update Reference Data

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#192]
@charlottedawson commented on [Tue Oct 09 2018](https://github.com/linz/qgis-buildings-plugin/issues/89)

### User Story

In order to update the reference data regularly as an LDA I want to create an update process using Change sets.

#### Acceptance Criteria
- [x] eg. Do not Delete and Replace.
- [x] Some are LDS Layers - can use their change sets
- [ ] Other non LDS Layers eg Suburbs
- [x] See Reference Data Schema for full list.

**Comment by MDavidson17** [comment]
Two new issues created:
changesets: https://github.com/linz/nz-buildings/issues/200
admin boundaries: https://github.com/linz/nz-buildings/issues/201
