### ISSUE TITLE
Generalisation process for Building Outlines to be used in Topo50 data.

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#195]
@charlottedawson commented on [Fri Mar 16 2018](https://github.com/linz/qgis-buildings-plugin/issues/8)

### User Story

As a Location Data Analyst I want to generalise building outlines so that they can be represented on a Topo50 map. 

#### Acceptance Criteria
- [ ] Promapp steps are followed. 
- [ ] Incorporate existing generalisation scripts into Github repos.

**Comment by dwsilk** [comment]
Moved to https://github.com/linz/qgis-buildingsgeneralisation-plugin
