### ISSUE TITLE
One building outline in both related and added tables

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#221]
### Bug Description
During QA, one of the related processes is to fix buildings where existing db has two buildings and the bulk load has one building, but the imagery shows there are two buildings. To fix this, the related buildings are first unlinked, and then the user exits the alter relationships tab, then selects the "one" outline to delete it. The user then goes back into the alter relationships tab, and selects the two buildings and presses the X buttom to add them back into the bulk load table. At some point in this process, multiple outlines with the same id are created.

#### Desktop
 - Environment: [e.g. Windows / DaaS / Ubuntu]
 - Relevant Software Versions [e.g. QGIS 2.18.21]

#### Screenshots

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by MDavidson17** [comment]
Bug has been identified in the find_related function, new issue created: https://github.com/linz/nz-buildings/issues/223
