### ISSUE TITLE
Setup db to allow reg user VAR permission

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-buildings#249]
### User Story

In order to reduce time in using the buildings db, as a LDA db regular user, I want the ability to run Vacuum, Analyse and Re-index (VAR) on the buildings tables.

Currently regular users don't have permissions to accomplish this task, but this could potentially be allowed by using SQL functions, though with some potential drawbacks I'm sure.

#### Acceptance Criteria
- [ ] ability of run VAR as a regular user
- [ ] ...
- [ ] ...

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by dwsilk** [comment]
`VACUUM` cannot be executed inside a function, so a function can't be created to provide elevated permissions.

> ERROR:  VACUUM cannot be executed from a function or multi-command string
