### ISSUE TITLE
Update Spec to send to supplier

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#252]
### User Story

In order to reduces issues found in the qa process as a LDA I want a more robust and detailed specification document with examples from our recent QA.

#### Acceptance Criteria
Include common scenarios such as :
- [x] Tanks - captured too large or square
- [ ] Buildings on edge of imagery
- [x] Missed huts

**Comment by jducnuigeen** [comment]
Details sent to Charlotte.
