### ISSUE TITLE
Fix Building Overlaps identified in QA

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#254]
### Bug Description
Overlaps were discovered in QA that we hadn't previously identified as issues. 

Two scenarios need to be fixed with buildings in production:
- When buildings have not been picked up by the comparisons process as they overlap the building but not the capture source area
- When buildings are a part of the areas in Canterbury where there are three sets of overlapping capture source areas. If the building outline was not in all three datasets there is overlap. 
- When buildings are split into 6 parts in Auckland but users were still using the whole Auckland imagery. If the building outline was outside of the capture source area but not the imagery users might still add it.

These outlines need to be fixed in the database, the 'old' building outlines needed to have the end lifespan attribute updated and the 'new' outline need to be linked to the same building id. 

#### Steps to Reproduce
1.  open buildings production outlines
2. zoom around the map at the borders/overlaps of capture source areas
3. observe some overlaps

#### Screenshots
Scenario One:
![image](https://user-images.githubusercontent.com/33814653/55766530-2956ee00-5ac9-11e9-9f11-c0f49e88692f.png)

Scenario Two:
![image](https://user-images.githubusercontent.com/33814653/55766550-3bd12780-5ac9-11e9-84f8-b58d07e6290f.png)

Scenario Three:
![image](https://user-images.githubusercontent.com/33814626/56002604-29e4c400-5d17-11e9-8edb-b879c0cc4db7.png)

**Comment by YingtingChen** [comment]
Steps to fix **Senario two:**


I. Find the "not removed" outlines

II. Copy and match the "removed" outline from previous dataset (using building_outline_id):

1. Get all the attributes. run intersect query for capture_source_id and the others from building_outlines table
2. Insert into bulk_load_outlines table
3. Insert into matched table

III. Delete the record in the removed table 

IV. "Publish" the new bulk load outline (load_buildings.sql):
1. Get building_id of the matched existing outline
2. Get attributes from the bulk_load_outlines
3. Insert building_outlines using the info above
4. Add a record into transferred table
5. End lifespan the old building_outline

V. "Compare" the added outline with the last loaded dataset(comparisons.py, compare_buildings.sql):
1. Insert into existing_subset_extracts table
2. Insert into matched table
3. Remove the record from added table

VI. "Publish" to finally remove the duplicate outlines:
1. Find the duplicate outline from the last dataset, update building_id to match the old one
2. End lifespan the old duplicate outline.

Note:

- This occurred in (Cant-1415, Waimakariri Urban, Cant1516) & (Waikato rural, Waikato urban, Auckland)
- Some cases might be `related` than `matched` relationship

**Comment by YingtingChen** [comment]
Steps to fix **Scenario One**:

I. Delete from added table
II. Insert into matched table
III. "Publish" to finally remove the duplicate outlines:
1. Find the duplicate outline from the last dataset, update building_id to match the old one
2. End lifespan the old duplicate outline

Note:
- This occurred in Waimakariri urban, Chch urban, Horizons
- Some cases might be `related` than `matched` relationship

**Comment by YingtingChen** [comment]
Steps to fix **Scenario Three**:
I. End lifespan using the production frame

**Comment by YingtingChen** [comment]
Reopen this issue as it was closed by the PR.

**Comment by YingtingChen** [comment]
New approach to fix the issue:

- [ ] For those overlapping **matched** buildings, create a script to 
- Update the old building outline's end_lifespan with the new building outline's begin_lifespan
- Update the new building outline's building_id with the old building outline's building_id
- Delete the new building_id that has now been unlinked


- [ ] For those overlapping **related** buildings, create a script to 
- add records into the nz-building-outlines lifecycle table
- To be updated

- [ ] For those different building outlines overlapped, edit the geometries

**Comment by charlottedawson** [comment]
@dwsilk @MDavidson17 Can we close this?

**Comment by dwsilk** [comment]
Yes, all fixed.
