### ISSUE TITLE
Investigate workflow improvements

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-buildings#275]
### User Story

As an LDA doing buildings QA, I want the workflow using the plugin to be as efficient as possible to enable the fastest QA possible.

1. Review as many scenarios where buildings had to be deleted, matched, or related in alter relationships.
2. Document these changes, possibly showing examples, with numbers of clicks
3. Prioritise scenarios in order in which they would save the most amount of time if changed.

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by jducnuigeen** [comment]
Examples of workflow improvements. I could demo this, as these would be good to discuss as a team:
S:\IndependentDatasets\BuildingOutlines\Workflow Improvements\Workflow_Improvements.pptx

**Comment by charlottedawson** [comment]
Great demo - have created issues as a result.
