### ISSUE TITLE
Move edit/add trigger to buttons in buildings toolbar

### ISSUE THREAD

**Issue by MDavidson17** [linz/nz-buildings#280]
### User Story

In order to open the edit/add building outlines dialog in the bulk load/production frames as a LDA I want the user to open these options using buttons in the buildings toolbar instead of selecting them from the tbtn dropdown. 

#### Acceptance Criteria
- [ ] create three new options in buildings tool bar when at editing stages of bulk load (add, edit geometry, edit attributes)
- [ ] create three new options in buildings tool bar for editing production (add, edit geometry, edit attributes)
- [ ] link buttons to edit outlines options
- [ ] remove existing tbtn process

**Comment by YingtingChen** [comment]
Done
