### ISSUE TITLE
Slicing External building eg garage.

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#291]
### User Story

In order to separate a garage from a house as a LDA I want a workflow that has less than 24 steps.

#### Acceptance Criteria
- [ ] ...
- [ ] ...
- [ ] ...

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by MDavidson17** [comment]
closed by https://github.com/linz/nz-buildings/pull/295
