### ISSUE TITLE
Integrate Buildings and LIQA into the same window for QA - Investigation

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#292]
### User Story
@dwsilk to elaborate
In order to [accomplish goal] as a [role] I want [capability] 
(optional: instead of [existing behaviour]).

#### Acceptance Criteria
- [ ] reuse liqa functionality
- [ ] use liqa to get qa outputs
- [ ] have buildings version of error inspector for qa

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by YingtingChen** [comment]
New issue created #293

**Comment by dwsilk** [comment]
Taking a different approach for now.
