### ISSUE TITLE
Report to ecopia on 2019 capture problems

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-buildings#304]
### Bug Description
As an LDA we want ecopia to understand what issues we discovered on the 2019 building capture, and thus need to create some documentation for this.

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by dwsilk** [comment]
Issue moved to [linz/topo-tasks #245](https://github.com/linz/topo-tasks/issues/245) via [**ZenHub**](https://www.zenhub.com/)
