### ISSUE TITLE
Check/setup VAR in function

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-buildings#305]
### User Story
This will fix #249 
In order to have an efficient database as a LDA I want the database to automatically Vacuum, Analyze and Reindex all tables, if possible, preferably in a function.

#### Acceptance Criteria
- [ ] Some means of VAR is accomplished automatically on the database.
- [ ] ...
- [ ] ...

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by dwsilk** [comment]
`VACUUM` is not possible inside a function.

> ERROR:  VACUUM cannot be executed from a function or multi-command string
