### ISSUE TITLE
Improve test coverage for published data

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#316]
### User Story

In order to have consistent testing of the DB as a LDA I want improve test coverage over the published dataset. 

#### Acceptance Criteria
- [ ] Improve test coverage for published data
- [ ] Update PGtap scripts to test more published data

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by dwsilk** [comment]
Duplicate of #273
