### ISSUE TITLE
Building Travis Tests Failing

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#321]
### Bug Description
Travis failing when creating postgis extension
@YingtingChen @dwsilk can you please update the details in this issue?

#### Desktop
 - Environment: [e.g. Windows / DaaS / Ubuntu]
 - Relevant Software Versions [e.g. QGIS 2.18.21]

#### Screenshots

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by YingtingChen** [comment]
It's likely to be a recent update in travis-ci. (see https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment). `Ubuntu Xenial 16.04` is now the default Travis CI build environment instead of previous version `Trusty`
