### ISSUE TITLE
Bug: Fix dates on related buildings in Taranaki

### ISSUE THREAD

**Issue by Ben-Cheng** [linz/nz-buildings#327]
### Bug Description
The overlapping area of buildings in Taranaki and Manawatu contains incorrect dates in the output for publishing to the LDS.

#### Steps to Reproduce
1. Follow the QA Workflow

#### Desktop
 - Environment: Windows

**Comment by dwsilk** [comment]
Schema migration issue, no code changes required. Already resolved by use of `sqitch` for future migrations.
