### ISSUE TITLE
Upgrade Buildings Plugin to QGIS 3.4+

### ISSUE THREAD

**Issue by dwsilk** [linz/nz-buildings#328]
### User Story

In order to continue to use and maintain the NZ Buildings tool on a supported software stack as an LDA I need this plugin upgraded and made compatible with QGIS 3.4+

#### Acceptance Criteria
- [x] Run `qgis2to3`
- [x] Run `qgisapi2finder`
- [x] Fix API breaks identified by the QGIS 2 API finder
- [x] Install in QGIS 3.4 and fix other API breaks that were not resolved by the tools above
- [x] Upgrade data dictionary
- [x] Test buildings <-> LIQA interactions
- [x] Upgrade Travis testing
- [x] Test in Windows
- [x] Test in DaaS
- [x] Release new version

**Comment by charlottedawson** [comment]
Plugin released
