### ISSUE TITLE
Vertices not deleting properly

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#331]
### User Story

In order to update the geometry of a polygon as a LDA I want the vertice tool to work the same way it does outside the building plugin.

#### Acceptance Criteria
- [ ] Must be able to delete consecutive vertices without having to click between them
- [ ] ...
- [ ] ...

Note: 
Vertices don’t delete properly – deleting consecutive vertices doesn’t work.  You have to re-click on each vertex with the mouse before you can delete it. 
(This may trigger something in the window)

**Comment by jducnuigeen** [comment]
![editing](https://user-images.githubusercontent.com/25912064/120398271-fd281680-c38d-11eb-9516-1fc38c116958.gif)

**Comment by jducnuigeen** [comment]
Unable to generate the error on a large local copy of the database on a large bulk load.

**Comment by Douglas-K** [comment]
The Postgres DB is planned to soon be upgraded, migrated to AWS, and be accessible from Linux instead of Windows.  This might resolve the issue.
The problem is also mitigated with less QA editing required in the database due to the new Acceptance QA and fix-ups applied directly to supplied data.
