### ISSUE TITLE
Move buildings 'remove small tanks' process to bulk load

### ISSUE THREAD

**Issue by MDavidson17** [linz/nz-buildings#338]
### User Story

In order to remove the unnecessary step of deleting a lot of buildings as an LDA doing buildings QA I want the find small tanks code added to bulk load and these buildings automatically removed (like small buildings are) 

#### Acceptance Criteria
- [x] small circular buildings are removed on bulk load
- [x] tests added

**Comment by pkinglinz** [comment]
blocked by github actions. Travis producing a Qt error, so if github actions implemented this will be resolved
