### ISSUE TITLE
Building QA: fail to find "bulk_load_" field in qa_missing_hut layer

### ISSUE THREAD

**Issue by Ben-Cheng** [linz/nz-buildings#342]
@YingtingChen commented on [Tue Nov 26 2019](https://github.com/linz/qgis-liqa-plugin/issues/270)

### Bug Description
"bulk_load_" field doesn't exist in qa layers that are from missing hut or shelter or bivouac checks. so the code would fail when it tries to find the field

#### Steps to Reproduce
1. Open bulk load frame
2. Open LIQA and run missing hut or shelter or bivouac, keep the qa layer and error inspector
3. Open edit dialog (edit attribute) and delete any one of the buildings
![image](https://user-images.githubusercontent.com/33814626/69595822-7b9f4c00-1065-11ea-92f9-9d5679a4d07e.png)

#### Desktop
 - Environment: Windows / DaaS / Ubuntu
 - Relevant Software Versions: QGIS 2.18.21

**Comment by dwsilk** [comment]
Fixed by #343
