### ISSUE TITLE
QgsHighlight not clearing on Windows10

### ISSUE THREAD

**Issue by MDavidson17** [linz/nz-buildings#346]
### Bug Description
When testing the buildings plugin on a QGIS3 windows 10 virtual machine the QgsHighlight in alter relationships and buildings/LIQA is not cleared when the selection is changed. 

This does not appear to be a problem on ubuntu 18 or windows 7

#### Steps to Reproduce
1. in QGIS3 on Windows 10
2. open buildings plugin and navigate to alter relationships
3. select a set of buildings
4. select another set of buildings
5. observe the previous highlight not cleared

#### Desktop
 - Environment: Windows 10
 - Relevant Software Versions QGIS 3.4.11

**Comment by dwsilk** [comment]
Works on real Windows 10 machines #wontfix

**Comment by oznerol2** [comment]
not windows 10 but QIG3 and QgisHighLight.cpp arent fully compatible

**Comment by dwsilk** [comment]
Cheers @oznerol2 - I note you've raised an issue on the QGIS repo, will keep an eye on it. We don't have a problem in our operational environments though.
