### ISSUE TITLE
Vertex editing disconnect

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-buildings#349]
### Bug Description
During alter relationships QA, more than one vertex cannot be edited after opening the edit geometry dialog, if a previous edit geometry dialog has been closed from a previous geometry editing session.

#### Steps to Reproduce
1. Open plugin, go to alter relationships.
2. Select a matched building outlines and unlink.
3. Open the edit geometry dialog, and edit a vertex of the bulk load, click save, then close the edit geometry dialog.
4. Open the edit geometry dialog again, and attempt to edit more than one vertex in the session.
5. More than one vertex will not be able to be edited.

#### Desktop
 - Environment: [e.g. Windows/ linux
 - QGIS 3.4

#### Screenshots

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by jducnuigeen** [comment]
Problem will be addressed by adjusting the `edit_cancel_clicked` function in both the
**bulk_load_frame.py** and **alter_building_relationship.py**
and changing `self.bulk_load_layer.geometryChanged.disconnect()`
to `self.bulk_load_layer.geometryChanged.disconnect(self.change_instance.geometry_changed)`

**Comment by YingtingChen** [comment]
> However, if you only put the above change, when adding a new outline you will get this error:
> 
> ```
> AttributeError: 'AddBulkLoad' object has no attribute 'geometry_changed' 
> Traceback (most recent call last):
>   File "C:/Users/jducnuigeen.AD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\buildings\gui\edit_dialog.py", line 239, in close_dialog
>     self.parent_frame.edit_cancel_clicked()
>   File "C:/Users/jducnuigeen.AD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\buildings\gui\alter_building_relationships.py", line 1828, in edit_cancel_clicked
>     self.lyr_bulk_load.geometryChanged.disconnect(self.change_instance.geometry_changed)
> AttributeError: 'AddBulkLoad' object has no attribute 'geometry_changed'
> ```

`AddBulkLoad` class doesn't have the `geometry_changed` function instead it's called `creator_geometry_changed`. so if you use `self.lyr_bulk_load.geometryChanged.disconnect(creator_geometry_changed)` under alter: L1819 `elif isinstance(self.change_instance, bulk_load_changes.AddBulkLoad):` it should work fine :smile_cat:

**Comment by jducnuigeen** [comment]
I just noticed that with the first change installed, when I split a building, I can't then edit the vertex of one of the split buildings for some reason.

**Comment by MDavidson17** [comment]
see https://github.com/linz/nz-buildings/issues/354 for these changes on production
