### ISSUE TITLE
Investigate optimising localities reference data update

### ISSUE THREAD

**Issue by pkinglinz** [linz/nz-buildings#358]
### User Story

Currently sql finds suburbs which have been added, deleted or changed. and processes these but taking in excess of 11hrs, due to 2000 suburb ids (approx 1/4).

Investigate difference as 2000 additions doesn't seem correct.

Could be due to slight changes in geom, find this difference and investigate these?

#### Acceptance Criteria
- [x] Investigate suburb changes
- [x] Create new issues
- [ ] ...

**Comment by dwsilk** [comment]
#360, #361, #363, #364 and #365 created.
