### ISSUE TITLE
Optimize Localities: Add only Suburbs and Localities

### ISSUE THREAD

**Issue by MDavidson17** [linz/nz-buildings#360]
### Bug Description
As an LDA running the suburb localities update on buildings. I want the process of inserting the new suburbs/localities optimized.

#### Description
The current function to find the added/new suburbs and localities in the nz_localities table finds 2062 new areas to be added. This is due to it not accounting for the attributes in the NZ_localities table that are not suburbs or localities (for example lakes/coastal bays). These areas were left out of the initial import as they do not contain buildings. 

To fix this the function `buildings_reference.suburb_locality_insert_new_areas()` in suburb_locality.sql needs to be updated to only insert features with the type of SUBURB or LOCALITY. 

This issue also requires an investigation into the ISLAND Type. As some are included in the buildings_reference.suburb_locality table. Are all to be included? are only the major ones with buildings currently included?

**Comment by Douglas-K** [comment]
Investigated  ISLAND type and found:
Islands with suburb_4th attributes are included in suburb_locality and those with no suburb_4th are excluded. We have decided to include all islands into the process so those with no suburb_4th need to be added in AND update process to create lds data to attribute "suburb_locality" from suburb_3rd etc.
#364

**Comment by Douglas-K** [comment]
Also found LAKE and INLAND BAY types exist in suburb_locality. These should be removed to be consistent with OFFSHORE BAY which is already excluded.
#363

**Comment by dwsilk** [comment]
To redo using `sqitch`
