### ISSUE TITLE
Optimize Localities: Changed suburbs/localities

### ISSUE THREAD

**Issue by MDavidson17** [linz/nz-buildings#361]
### User Story

In order to optimize the updating of the buildings suburb/localities as an LDA I want the 'changed' suburb/localities to differentiate between attribute change and geometry change.

#### Description
Currently the function `buildings_reference.suburb_locality_update_suburb_locality()` finds and returns the ids of all the suburb/localities that have changed in some form. This includes both the geometry and the attributes. 
All these ids are returned and added to a list. If a building has an id in this list as it's external_suburb_locality_id a check is run (using ST_Intersection) to re-assign the id. 
Currently 123 'changes' are returned, however, 101 of these are attribute changes (name changes) these do not need to be checked using ST_intersection. To optimize the process of updating suburb/localities if the 101 attribute changes can be updated and 'ignored' the processing may improve. 

#### Acceptance Criteria
- [ ] differentiate between attribute updates and geometry updates
- [ ] only run the st_intersection check on geometry updates
- [ ] test the speed of this on a copy of the db

**Comment by dwsilk** [comment]
Will be fixed by the same function that has been created for #371.
