### ISSUE TITLE
Optimize Localities: Remove lakes and inland bays

### ISSUE THREAD

**Issue by Douglas-K** [linz/nz-buildings#363]
### Bug Description
As an LDA running the suburb localities update on buildings, I want the process to exclude LAKEs and INLAND BAYs.

#### Description
Currently LAKEs and INLAND BAYs are included in suburb_locality. These should be removed.  OFFSHORE BAYs are already excluded. Buildings in LAKEs and INLAND BAYs should instead be linked to the closest LOCALITY/SUBURB/ISLAND.

There are currently 51 buildings in LAKEs:
```sql
SELECT b.*, l.suburb_4th
FROM buildings.building_outlines b
JOIN buildings_reference.suburb_locality s USING (suburb_locality_id)
JOIN admin_bdys.nz_locality l ON s.external_suburb_locality_id = l.id
WHERE l.type = 'LAKE'
```

There are currently 18 buildings in INLAND BAYs:
```sql
SELECT b.*, l.suburb_4th
FROM buildings.building_outlines b
JOIN buildings_reference.suburb_locality s USING (suburb_locality_id)
JOIN admin_bdys.nz_locality l ON s.external_suburb_locality_id = l.id
WHERE l.type = 'INLAND BAY'
```

#### Acceptance Criteria
- [x] Write code to update locality ID field for buildings currently in LAKEs and INLAND BAYs (publish to buildings_lds schema will need to be re-rerun some time to repopulate the suburb_locality_id field)
- [x] Write code to delete LAKEs and INLAND BAYs from buildings_reference.suburb_locality

**Comment by Douglas-K** [comment]
Completed code is here:
https://gist.github.com/Douglas-K/2b9dea5fa3164f5ffadf81af2133037d

**Comment by dwsilk** [comment]
Run-through and test completed on full dataset, looks good.
