### ISSUE TITLE
Put Real Buildings Data into Test Data

### ISSUE THREAD

**Issue by bencheng1990** [linz/nz-buildings#396]
### User Story
In order to test on real data as a LDA I want real buildings data to be in the test data

### Acceptance Criteria
- [x] Real buildings data in the test dataset
- [x] Ensure buildings tests still pass

Remarks:
https://confluence.linz.govt.nz/display/GEOD/Updating+and+Creating+Test+Data
To change the test data you can follow the steps linked above to create the test data. Then add the buildings to the map canvas and edit them. The command `make dump_schema` will dump the changes you have made to the correct file removing manual intermediate steps.

There are two databases: one for the plugin and one for the db. We should start with the plugin one: `nz-buildings-plugin-db`

**Comment by jducnuigeen** [comment]
pg_dump from DaaS buildings db was done using this command:
`pg_dump -h prdassgeo02.ad.linz.govt.nz -p 5432 -U "RClarke" -F c -Z 9 -x -v -O -f "G:\buildings\buildings.backup" -n buildings -n buildings_common -n buildings_lds -n buildings_bulk_load -n buildings_reference -T "buildings_reference.fenz_supermarkets" -T "buildings_reference.hospitals" -T "buildings_reference.schools" -T "buildings_reference.tasman_supermarkets" -T "buildings_reference.supermarkets" -T "buildings_reference.x_splits" -T "buildings_reference.fenz_supermarkets_id_seq" "linz_db"`

This dumped everything - data and schema. If you only wanted schema, you would add the -s flag before the -n flags.

To restore to the local db:
`pg_restore -h localhost -p 5432 -d linz_db -U postgres -O -v -x  "/media/jan/ADATA UFD/Buildings_dump/buildings.backup"`
