### ISSUE TITLE
Splitting buildings out of range

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-buildings#460]
### Bug Description
When attempting to split building outlines during bulk load liqa checks,, an error is generated:
An error has occurred while executing Python code: 

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:/Users/jducnuigeen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\buildings\gui\bulk_load_changes.py", line 910, in edit_save_clicked
    self.parent_frame.reload_bulk_load_layer()
  File "C:/Users/jducnuigeen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\buildings\gui\bulk_load_frame.py", line 681, in reload_bulk_load_layer
    self.cb_added_clicked(False)
  File "C:/Users/jducnuigeen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\buildings\gui\bulk_load_frame.py", line 369, in cb_added_clicked
    added_category[0].setData(Qt.Unchecked, Qt.CheckStateRole)
IndexError: list index out of range

Strangely, this wasn't happening earlier in the same day, but as soon as it happened once, it happens every split thereafter.

#### Steps to Reproduce
1. Split large building
2. Error above occurs

#### Desktop
 - Environment: [e.g. Windows / DaaS / Ubuntu]
 - Relevant Software Versions [e.g. QGIS 3.10]

#### Screenshots

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by dwsilk** [comment]
Might be related to splitting a building with a hole but needs more investigation.

**Comment by jducnuigeen** [comment]
Unable to generate the error on a linux machine using a large bulk load on a local copy of the existing database.

**Comment by Douglas-K** [comment]
The Postgres DB is planned to soon be upgraded, migrated to AWS, and be accessible from Linux instead of Windows.  This might resolve the issue.
The problem is also mitigated with less QA editing required in the database due to the new Acceptance QA and fix-ups applied directly to supplied data.
